CREATE TABLE USERS(
  COD_USER BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'THE PRIMARY KEY OF THE USER',
  COD_PEOPLE BIGINT COMMENT 'COD OF PEOPLE',
  COD_TIPUSERS BIGINT COMMENT 'COD OF TYPE OF USERS',
  email,
  password, 
  email_verified_at,
  photo_path
  API_TOKEN VARCHAR(6) NOT NULL COMMENT 'TOKEN DE ACCESO',
  IND_USR ENUM('1', '0') NOT NULL COMMENT 'IND OF THE USER TO ACCESS THE SYSTEM, 0=INACTIVE 1=ACTIVE',
  IND_INS ENUM('1', '0') NOT NULL COMMENT 'IND OF THE FIRST TIME IN THE SYSTEM.',
  USR_ADD VARCHAR(30) NOT NULL COMMENT 'USER THAT ADDED THIS ROW',
  USR_UPD VARCHAR(30) NOT NULL COMMENT 'USER WHO MODIFIED THIS ROW',
  DAT_ADD DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATE THAT THIS ROW WERE ADDED',
  DAT_UPD DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATE THIS ROW WAS MODIFIED',
  FOREIGN KEY `FK_PEOADD_PEOUSR`(`COD_PEOPLE`) REFERENCES `PA_PEOPLE`(`COD_PEOPLE`) ON DELETE CASCADE,
  FOREIGN KEY `FK_TIPUSE_USERS` (`COD_TIPUSERS`) REFERENCES `PA_TIPUSERS`(`COD_TIPUSERS`) ON DELETE CASCADE
) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;



CREATE TABLE PA_PEOPLE(
  COD_PEOPLE BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'COD OF THE PERSON',
  ID VARCHAR(60) NOT NULL UNIQUE COMMENT 'THE ID OF THE PERSON, IT COULD THE PASSPORT OR NATIONAL ID',
  TIP_DOCUMENT ENUM("ID", "PASSPORT", "LICENSE") NOT NULL COMMENT "THE TYPE OF DOCUMENTATION OF THE PERSON",,
  FIRSTNAME VARCHAR(120) NOT NULL COMMENT 'THE FIRTS NAME OF A PERSON',
  MIDDLENAME VARCHAR(120) NOT NULL COMMENT 'THE MIDDLE NAME OF A PERSON',
  LASTNAME VARCHAR(120) NOT NULL COMMENT 'THE LAST NAME OF A PERSON',
  AGE TINYINT NOT NULL COMMENT 'THE AGE OF A PERSON',
  USR_ADD VARCHAR(30) NOT NULL COMMENT 'USER THAT ADDED THIS ROW',
  USR_UPD VARCHAR(30) NOT NULL COMMENT 'USER WHO MODIFIED THIS ROW',
  DAT_ADD DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATE THAT THIS ROW WERE ADDED',
  DAT_UPD DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATE THIS ROW WAS MODIFIED'
) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;

CREATE TABLE PA_ADDRESS(
  COD_ADDRESS BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'THE PRIMARY KEY OF THE ADDRESS',
  COD_CITY BIGINT COMMENT 'COD OF THE CITY',
  ADDRESS VARCHAR(1000) NOT NULL COMMENT 'THE ADDRESS',
  TYP_ADDRESS ENUM('H', 'W', 'A') NOT NULL COMMENT 'TYPE OF ADDRESS H:HOME W:WORK A:ADDRESS',
  USR_ADD VARCHAR(30) NOT NULL COMMENT 'USER THAT ADDED THIS ROW',
  USR_UPD VARCHAR(30) NOT NULL COMMENT 'USER WHO MODIFIED THIS ROW',
  DAT_ADD DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATE THAT THIS ROW WERE ADDED',
  DAT_UPD DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATE THIS ROW WAS MODIFIED',
  FOREIGN KEY `FK_ADDRESS_CITIES`(`COD_CITY`) REFERENCES `PA_CITIES`(`COD_CITY`) ON DELETE CASCADE
) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;

CREATE TABLE PA_PHONES(
  COD_PHONE BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'COD OF A PHONE NUMBER',
  NUM_AREA TINYINT NOT NULL COMMENT 'NUMBER OF AREA TO CALL',
  NUM_PHONE INT(10) NOT NULL COMMENT 'PHONE NUMBER OF THE PERSON',
  TYP_PHONE ENUM('H', 'O', 'C') NOT NULL COMMENT 'THE TYPE OF PHONE NUMBER H:HOME O:OFFICE C:CELLPHONE',
  USR_ADD VARCHAR(30) NOT NULL COMMENT 'USER THAT ADDED THIS ROW',
  USR_UPD VARCHAR(30) NOT NULL COMMENT 'USER WHO MODIFIED THIS ROW',
  DAT_ADD DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATE THAT THIS ROW WERE ADDED',
  DAT_UPD DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATE THIS ROW WAS MODIFIED'
) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;

/*TABLE OF CUSTOMERS*/
CREATE TABLE PA_CUSTOMERS(
  COD_CUSTOMER BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'THE PRYMARY KEY OF THE CUSTOMERS',
  COD_PEOPLE BIGINT COMMENT 'COD OF PEOPLE',
  COD_TYPCUST BIGINT COMMENT 'COD OF TYPE OF CUSTOMER',
  DES_COMPANY VARCHAR(255) COMMENT 'IF THE CUSTOMER WORKS ON A COMPANY',
  IND_CUSTOMER ENUM('1', '0') NOT NULL COMMENT 'IND OF THE CUSTOMER',
  USR_ADD VARCHAR(30) NOT NULL COMMENT 'USER THAT ADDED THIS ROW',
  DAT_ADD DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATE THAT THIS ROW WERE ADDED',
  DAT_UPD DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATE THIS ROW WAS MODIFIED',
  FOREIGN KEY `FK_CUST_PEOP` (`COD_PEOPLE`) REFERENCES `PA_PEOPLE`(`COD_PEOPLE`) ON DELETE CASCADE,
  FOREIGN KEY `FK_TYCU_CUST` (`COD_TYPCUST`) REFERENCES `PA_TYPCUSTOMERS` (`COD_TYPCUST`) ON DELETE CASCADE
) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;


CREATE TABLE PA_TIPUSERS(
  COD_TIPUSERS BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'THE PRIMARY KEY OF TYPE OF USER',
  NOM_TYPE VARCHAR(120) NOT NULL UNIQUE COMMENT 'THE NAME OF THE TYPE OF USER',
  DES_TYPE VARCHAR(2000) NOT NULL COMMENT 'DESCRIPTION OF THE TYPE OF USER'
USR_ADD VARCHAR(30) NOT NULL COMMENT 'USER THAT ADDED THIS ROW',
USR_UPD VARCHAR(30) NOT NULL COMMENT 'USER WHO MODIFIED THIS ROW',
DAT_ADD DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATE THAT THIS ROW WERE ADDED',
DAT_UPD DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATE THIS ROW WAS MODIFIED'
) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;



*******************************************

CREATE TABLE PA_EMAILS(
  COD_EMAIL BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT 'RELATIONSHIP BETWEEN PEOPLE AND PHONES',
  USEREMAIL VARCHAR(200) COMMENT 'USER OF THE EMAIL ADDRESS',
  SERVEREMAIL VARCHAR(200) COMMENT 'SERVER OF THE EMAIL ADDRESS',
  TYP_EMAIL ENUM('P', 'O') COMMENT 'P:personal O:office',,
  USR_ADD VARCHAR(30) NOT NULL COMMENT 'USER THAT ADDED THIS ROW',
  USR_UPD VARCHAR(30) NOT NULL COMMENT 'USER WHO MODIFIED THIS ROW',
  DAT_ADD DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'DATE THAT THIS ROW WERE ADDED',
  DAT_UPD DATETIME NOT NULL ON UPDATE CURRENT_TIMESTAMP COMMENT 'DATE THIS ROW WAS MODIFIED'
) ENGINE = INNODB CHARACTER SET UTF8 COLLATE UTF8_UNICODE_CI;






























































DELIMITER $$
CREATE  PROCEDURE `UPD_TYPEUSER_HAS_PERMIS`(IN `COD_PERMISOS` VARCHAR(60), IN `COD_TYPEUSERS` VARCHAR(250), IN `USR_ADD` VARCHAR(30))
BEGIN
START TRANSACTION;
IF COD_TYPEUSERS THEN 
INSERT INTO
  `MOD_typeusers_has_permisos`(`COD_PERMISOS`, `COD_TYPEUSERS`)
VALUES
  (COD_PERMISOS, COD_TYPEUSERS);
ELSEIF   THEN 
DELETE FROM 
  `MOD_typeusers_has_permisos` WHERE (`COD_PERMISOS`, `COD_TYPEUSERS`)
VALUES
  (COD_PERMISOS, COD_TYPEUSERS)

ENDIF

COMMIT;
END$$
DELIMITER ;