DELIMITER $$ 
CREATE PROCEDURE `INS_PASS_RESET`(
  IN `EMAIL` VARCHAR(120),
  IN `API_TOKEN` VARCHAR(120),
) BEGIN START TRANSACTION;
INSERT INTO
  `SE_pass_resets`(`EMAIL`, `API_TOKEN`)
VALUES
(EMAIL,API_TOKEN)
END$$ 
DELIMITER ;